// <auto-generated />
namespace AcunMedya.Restaruantly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adminpanel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adminpanel));
        
        string IMigrationMetadata.Id
        {
            get { return "202502051912115_adminpanel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
