// <auto-generated />
namespace AcunMedya.Restaruantly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig1productcategorylationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1productcategorylationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202501291810056_mig1productcategorylationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
